apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 389
    targetPort: ldap
    protocol: TCP
    name: ldap
  selector:
    app: {{ template "fullname" . }}
