apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
  {{- if .Values.nginx.service }}
  {{- range $key, $value := .Values.nginx.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  type: {{ .Values.nginx.service.type | quote }}
  ports:
  - port: 80
    {{- if .Values.nginx.service.nodePort }}
    nodePort: {{ .Values.nginx.service.nodePort }}
    {{- end }}
    name: http
  - port: 443
    {{- if .Values.nginx.service.nodeSslPort }}
    nodePort: {{ .Values.nginx.service.nodeSslPort }}
    {{- end }}
    name: https
  {{- if .Values.nginx.monitoring }}
  - port: 18080
    name: monitoring
  {{- end }}
  selector:
    app: {{ template "fullname" . }}