# Default values for samba-ad-dc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: builditdigital/samba-ad-dc
  tag: latest
  pullPolicy: Always
service:
  name: samba-ad-dc
  type: NodePort
  externalPort: 389
  internalPort: 389
resources:
  limits:
    cpu: 100m
    memory: 96Mi
  requests:
    cpu: 100m
    memory: 64Mi
persistence:
  enabled: true
  storageClass: generic
  accessMode: ReadWriteOnce
  size: 128Mi
ad:
 realm: corp.riglet.io
 password: Local123
 strictTls: false
