apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
data:
  dh.pem: {{ .Values.openvpn.dhPem }}
  certs.p12: {{ .Values.openvpn.certsP12 }}
  ldap.pass: {{ .Values.openvpn.ldapPass }}